// <auto-generated />
using System;
using FinanceManagement.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FinanceManagement.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FinanceManagement.API.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Icon = "payments",
                            Name = "Salary",
                            Type = "income"
                        },
                        new
                        {
                            Id = 2,
                            Icon = "work",
                            Name = "Freelance",
                            Type = "income"
                        },
                        new
                        {
                            Id = 3,
                            Icon = "trending_up",
                            Name = "Investments",
                            Type = "income"
                        },
                        new
                        {
                            Id = 4,
                            Icon = "restaurant",
                            Name = "Food & Dining",
                            Type = "expense"
                        },
                        new
                        {
                            Id = 5,
                            Icon = "directions_car",
                            Name = "Transportation",
                            Type = "expense"
                        },
                        new
                        {
                            Id = 6,
                            Icon = "home",
                            Name = "Housing",
                            Type = "expense"
                        },
                        new
                        {
                            Id = 7,
                            Icon = "bolt",
                            Name = "Utilities",
                            Type = "expense"
                        },
                        new
                        {
                            Id = 8,
                            Icon = "movie",
                            Name = "Entertainment",
                            Type = "expense"
                        },
                        new
                        {
                            Id = 9,
                            Icon = "local_hospital",
                            Name = "Healthcare",
                            Type = "expense"
                        },
                        new
                        {
                            Id = 10,
                            Icon = "shopping_cart",
                            Name = "Shopping",
                            Type = "expense"
                        });
                });

            modelBuilder.Entity("FinanceManagement.API.Models.Transaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Transactions");
                });
#pragma warning restore 612, 618
        }
    }
}
